# CONSTANTS
MIN_HOUR = 1
MAX_HOUR = 100
MIN_CLASSROOM_CAP = 20
MAX_CLASSROOM_CAP = 400
MIN_VERSION_NUM = 1
MAX_VERSION_NUM = 3
MIN_CFU = 6
MAX_CFU = 10
    # per comando -a:f
SEMESTER_NUM_BS = 6
SEMESTER_NUM_MS = 4
MIN_COURSE_OF_STUDY = 1
MAX_COURSE_OF_STUDY = 4
    # per comando -i:c
MIN_ACADEMIC_YEAR = 2000
MAX_ACADEMIC_YEAR = 2025
    # per comando -s
SESSION_1_AND_2_DURATION = 41
SESSION_3_DURATION = 27
    # per funzione "generateDate" senza argomenti per AAref
MIN_YEAR = 2024
MAX_YEAR = 2024
    # per funzione "generateSubPatternExamOrg"
MIN_EXAM_DURATION = 60
MAX_EXAM_DURATION = 240
STEP_EXAM = 10
MIN_ENTRANCE_TIME = 5
MAX_ENTRANCE_TIME = 10
STEP_ENTRANCE = 5
MIN_EXIT_TIME = 5
MAX_EXIT_TIME = 15
STEP_EXIT = 5
MIN_PARTECIPANTS = 10
MAX_PARTECIPANTS = 400
    # per funzione "generateSubPatternGroupedCourses"
MIN_GROUPED_COURSES = 1
MAX_GROUPED_COURSES = 6
    # per funzione "generateEndedCourses"
MIN_ENDED_COURSES = 0
MAX_ENDED_COURSES = 6
    # per funzione "generateSubPatternUnavailability"
MIN_PROF_UNAVAIL_NUM = 0
MAX_PROF_UNAVAIL_NUM = 8
MIN_UNAVAIL_DURATION = 7
MAX_UNAVAIL_DURATION = 14

